[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "picarx"
authors = [
  { name="SunFounder", email="service@sunfounder.com" },
]
description = "Library for SunFounder PiCar-X robot car"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dynamic = ["version"]

dependencies = [
  'mammoth_websocket @ git+https://github.com/sunfounder/mammoth_websocket@main',
  'readchar',
  'piper-tts',
  'sox',
  'openai',
  'openai-whisper',
  'SpeechRecognition',
]

[tool.setuptools]
include-package-data = true
packages = [
  "picarx",
  "picarx.musics",
  "picarx.sounds",
]

[project.urls]
"Homepage" = "https://github.com/sunfounder/picar-x"
"Bug Tracker" = "https://github.com/sunfounder/picar-x/issues"

[tool.setuptools.dynamic]
version = {attr = "picarx.version.__version__"}
